from pptx import Presentation
from pptx.util import Inches

def create_ppt(df_pivot, fig):
    prs = Presentation()
    
    # Slide 1: Title
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = "Business Intelligence Report"
    slide.placeholders[1].text = "Generated by your AI App"

    # Slide 2: The Data Table
    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = "Pivot Table Summary"
    # (Logic to add table to slide goes here)

    # Slide 3: The Chart
    # We save the Plotly chart as an image and put it on a slide
    fig.write_image("temp_chart.png")
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    slide.shapes.add_picture("temp_chart.png", Inches(1), Inches(1), width=Inches(8))
    
    ppt_output = BytesIO()
    prs.save(ppt_output)
    return ppt_output.getvalue()
